### ISSUE TITLE
Wrong Regex Anchor Being Used Most Everywhere

### ISSUE THREAD

**Issue by sshaw** [westonganger/rearmed-rb#3]
```
irb [2.5.0] (rearmed-rb)$ Rearmed::String.valid_integer?("ABC\n123")
=> true
irb [2.5.0] (rearmed-rb)$ Rearmed::String.valid_integer?("")
=> true
```

Need to use `\A` and `\z` instead of `^` and `$` and drop `\d*` for `\d+`.

**Comment by westonganger** [comment]
Thanks for pointing this out. I have just released `v2.0.2` which tests against and fixes these cases.
